// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CloseButtonController from "./close_button_controller"
application.register("close-button", CloseButtonController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import TagsInputController from "./tags_input_controller"
application.register("tags-input", TagsInputController)
